// Auto-generated by scripts/sync_ncbi_bibliography.ps1
// Source: NCBI My Bibliography + PubMed efetch. Manual edits will be overwritten.
window.publicationsData = [
    {
        "year":  2025,
        "title":  "Multiscale structure of chromatin condensates explains phase separation and material properties.",
        "authors":  "Huabin Zhou, Jan Huertas, M Julia Maristany, Kieran Russell, June Ho Hwang, Run-Wen Yao, Nirnay Samanta, Joshua Hutchings, Ramya Billur, Momoko Shiozaki, Xiaowei Zhao, Lynda K Doolittle, Bryan A Gibson, Andrea Soranno, Margot Riggi, Jorge R Espinosa, Zhiheng Yu, Elizabeth Villa, Rosana Collepardo-Guevara#, Michael K Rosen#",
        "journal":  "Science",
        "citation":  "390(6777):eadv6588",
        "image":  "publication-media/2025_Science_1.png",
        "imageAlt":  "Figure preview for Science 2025 chromatin condensates paper",
        "sourceUrl":  "https://pubmed.ncbi.nlm.nih.gov/41343645/",
        "links":  [
                      {
                          "url":  "https://pubmed.ncbi.nlm.nih.gov/41343645/",
                          "label":  "PubMed"
                      },
                      {
                          "url":  "https://pmc.ncbi.nlm.nih.gov/articles/PMC12929043/",
                          "label":  "PMC"
                      },
                      {
                          "url":  "https://doi.org/10.1126/science.adv6588",
                          "label":  "DOI"
                      }
                  ]
    },
    {
        "year":  2025,
        "title":  "NUDT5 regulates purine metabolism and thiopurine sensitivity by interacting with PPAT.",
        "authors":  "Zheng Wu*, Phong T Nguyen*, Varun Sondhi, Run-Wen Yao, Zhifang Lu, Tao Dai, Jui-Chung Chiang, Feng Cai, Imani M Williams, Eliot B Blatt, Zengfu Shang, Ling Cai, Jing Zhang, Mya D Moore, Islam Alshamleh, Xiangyi Li, Tamaratare Ogu, Lauren G Zacharias, Rainah Winston, Joao S Patricio, Xandria Johnson, Wei-Min Chen, Qian Cong, Thomas P Mathews, Yuanyuan Zhang, Limei Zhang, Ralph J DeBerardinis#",
        "journal":  "Science",
        "citation":  "390(6778):1134-1142",
        "image":  "publication-media/2025_Science_2.png",
        "sourceUrl":  "https://pubmed.ncbi.nlm.nih.gov/41196949/",
        "links":  [
                      {
                          "url":  "https://pubmed.ncbi.nlm.nih.gov/41196949/",
                          "label":  "PubMed"
                      },
                      {
                          "url":  "https://pmc.ncbi.nlm.nih.gov/articles/PMC12853130/",
                          "label":  "PMC"
                      },
                      {
                          "url":  "https://doi.org/10.1126/science.adx9717",
                          "label":  "DOI"
                      }
                  ]
    },
    {
        "year":  2024,
        "title":  "Advanced surface passivation for high-sensitivity studies of biomolecular condensates.",
        "authors":  "Run-Wen Yao, Michael K Rosen#",
        "journal":  "PNAS",
        "citation":  "121(22):e2403013121",
        "image":  "publication-media/2024_PNAS.png",
        "sourceUrl":  "https://pubmed.ncbi.nlm.nih.gov/38781207/",
        "links":  [
                      {
                          "url":  "https://pubmed.ncbi.nlm.nih.gov/38781207/",
                          "label":  "PubMed"
                      },
                      {
                          "url":  "https://pmc.ncbi.nlm.nih.gov/articles/PMC11145189/",
                          "label":  "PMC"
                      },
                      {
                          "url":  "https://doi.org/10.1073/pnas.2403013121",
                          "label":  "DOI"
                      }
                  ]
    },
    {
        "year":  2023,
        "title":  "Nucleolar URB1 ensures 3\u0027 ETS rRNA removal to prevent exosome surveillance.",
        "authors":  "Lin Shan*, Guang Xu*, Run-Wen Yao, Peng-Fei Luan, Youkui Huang, Pei-Hong Zhang, Yu-Hang Pan, Lin Zhang, Xiang Gao, Ying Li, Shi-Meng Cao, Shuai-Xin Gao, Zheng-Hu Yang, Siqi Li, Liang-Zhong Yang, Ying Wang, Catharine C L Wong, Li Yu, Jinsong Li, Li Yang, Ling-Ling Chen#",
        "journal":  "Nature",
        "citation":  "615(7952):526-534",
        "image":  "publication-media/2023_Nature.png",
        "sourceUrl":  "https://pubmed.ncbi.nlm.nih.gov/36890225/",
        "links":  [
                      {
                          "url":  "https://pubmed.ncbi.nlm.nih.gov/36890225/",
                          "label":  "PubMed"
                      },
                      {
                          "url":  "https://doi.org/10.1038/s41586-023-05767-5",
                          "label":  "DOI"
                      }
                  ]
    },
    {
        "year":  2021,
        "title":  "An optimized fixation method containing glyoxal and paraformaldehyde for imaging nuclear bodies.",
        "authors":  "Run-Wen Yao, Peng-Fei Luan, Ling-Ling Chen#",
        "journal":  "RNA",
        "citation":  "27(6):725-733",
        "image":  "publication-media/2021_RNA.png",
        "sourceUrl":  "https://pubmed.ncbi.nlm.nih.gov/33846273/",
        "links":  [
                      {
                          "url":  "https://pubmed.ncbi.nlm.nih.gov/33846273/",
                          "label":  "PubMed"
                      },
                      {
                          "url":  "https://pmc.ncbi.nlm.nih.gov/articles/PMC8127994/",
                          "label":  "PMC"
                      },
                      {
                          "url":  "https://doi.org/10.1261/rna.078671.120",
                          "label":  "DOI"
                      }
                  ]
    },
    {
        "year":  2019,
        "title":  "Cellular functions of long noncoding RNAs.",
        "authors":  "Run-Wen Yao*, Yang Wang*, Ling-Ling Chen#",
        "journal":  "Nature Cell Biology",
        "citation":  "21(5):542-551",
        "image":  "publication-media/2019_NCB.png",
        "sourceUrl":  "https://pubmed.ncbi.nlm.nih.gov/31048766/",
        "links":  [
                      {
                          "url":  "https://pubmed.ncbi.nlm.nih.gov/31048766/",
                          "label":  "PubMed"
                      },
                      {
                          "url":  "https://doi.org/10.1038/s41556-019-0311-8",
                          "label":  "DOI"
                      }
                  ]
    },
    {
        "year":  2019,
        "title":  "Dynamic Imaging of RNA in Living Cells by CRISPR-Cas13 Systems.",
        "authors":  "Liang-Zhong Yang*, Yang Wang*, Si-Qi Li, Run-Wen Yao, Peng-Fei Luan, Huang Wu, Gordon G Carmichael, Ling-Ling Chen#",
        "journal":  "Molecular Cell",
        "citation":  "76(6):981-997.e7",
        "image":  "publication-media/2019_MC_1.png",
        "sourceUrl":  "https://pubmed.ncbi.nlm.nih.gov/31757757/",
        "links":  [
                      {
                          "url":  "https://pubmed.ncbi.nlm.nih.gov/31757757/",
                          "label":  "PubMed"
                      },
                      {
                          "url":  "https://doi.org/10.1016/j.molcel.2019.10.024",
                          "label":  "DOI"
                      }
                  ]
    },
    {
        "year":  2019,
        "title":  "Linking RNA Processing and Function.",
        "authors":  "Run-Wen Yao, Chu-Xiao Liu, Ling-Ling Chen#",
        "journal":  "Cold Spring Harbor symposia on quantitative biology",
        "citation":  "84:67-82",
        "image":  "publication-media/2019_CSHL_1.png",
        "sourceUrl":  "https://pubmed.ncbi.nlm.nih.gov/32019863/",
        "links":  [
                      {
                          "url":  "https://pubmed.ncbi.nlm.nih.gov/32019863/",
                          "label":  "PubMed"
                      },
                      {
                          "url":  "https://symposium.cshlp.org/content/84/67",
                          "label":  "DOI"
                      }
                  ]
    },
    {
        "year":  2019,
        "title":  "Nascent Pre-rRNA Sorting via Phase Separation Drives the Assembly of Dense Fibrillar Components in the Human Nucleolus.",
        "authors":  "Run-Wen Yao*, Guang Xu*, Ying Wang, Lin Shan, Peng-Fei Luan, Yang Wang, Man Wu, Liang-Zhong Yang, Yu-Hang Xing, Li Yang, Ling-Ling Chen#",
        "journal":  "Molecular Cell",
        "citation":  "76(5):767-783.e11",
        "image":  "publication-media/2019_MC_2.png",
        "sourceUrl":  "https://pubmed.ncbi.nlm.nih.gov/31540874/",
        "links":  [
                      {
                          "url":  "https://pubmed.ncbi.nlm.nih.gov/31540874/",
                          "label":  "PubMed"
                      },
                      {
                          "url":  "https://doi.org/10.1016/j.molcel.2019.08.014",
                          "label":  "DOI"
                      }
                  ]
    },
    {
        "year":  2018,
        "title":  "Genome-wide screening of NEAT1 regulators reveals cross-regulation between paraspeckles and mitochondria.",
        "authors":  "Yang Wang*, Shi-Bin Hu*, Meng-Ran Wang*, Run-Wen Yao, Di Wu, Li Yang, Ling-Ling Chen#",
        "journal":  "Nature Cell Biology",
        "citation":  "20(10):1145-1158",
        "image":  "publication-media/2018_NCB.png",
        "sourceUrl":  "https://pubmed.ncbi.nlm.nih.gov/30250064/",
        "links":  [
                      {
                          "url":  "https://pubmed.ncbi.nlm.nih.gov/30250064/",
                          "label":  "PubMed"
                      },
                      {
                          "url":  "https://doi.org/10.1038/s41556-018-0204-2",
                          "label":  "DOI"
                      }
                  ]
    },
    {
        "year":  2017,
        "title":  "Coordinated circRNA Biogenesis and Function with NF90/NF110 in Viral Infection.",
        "authors":  "Xiang Li*, Chu-Xiao Liu*, Wei Xue*, Yang Zhang, Shan Jiang, Qing-Fei Yin, Jia Wei, Run-Wen Yao, Li Yang#, Ling-Ling Chen#",
        "journal":  "Molecular Cell",
        "citation":  "67(2):214-227.e7",
        "image":  "publication-media/2017_MC.png",
        "sourceUrl":  "https://pubmed.ncbi.nlm.nih.gov/28625552/",
        "links":  [
                      {
                          "url":  "https://pubmed.ncbi.nlm.nih.gov/28625552/",
                          "label":  "PubMed"
                      },
                      {
                          "url":  "https://doi.org/10.1016/j.molcel.2017.05.023",
                          "label":  "DOI"
                      }
                  ]
    },
    {
        "year":  2017,
        "title":  "SLERT Regulates DDX21 Rings Associated with Pol I Transcription.",
        "authors":  "Yu-Hang Xing*, Run-Wen Yao*, Yang Zhang*, Chun-Jie Guo, Shan Jiang, Guang Xu, Rui Dong, Li Yang, Ling-Ling Chen#",
        "journal":  "Cell",
        "citation":  "169(4):664-678.e16",
        "image":  "publication-media/2017_Cell.png",
        "sourceUrl":  "https://pubmed.ncbi.nlm.nih.gov/28475895/",
        "links":  [
                      {
                          "url":  "https://pubmed.ncbi.nlm.nih.gov/28475895/",
                          "label":  "PubMed"
                      },
                      {
                          "url":  "https://doi.org/10.1016/j.cell.2017.04.011",
                          "label":  "DOI"
                      }
                  ]
    },
    {
        "year":  2016,
        "title":  "Shedding light on paraspeckle structure by super-resolution microscopy.",
        "authors":  "Shi-Bin Hu, Run-Wen Yao, Ling-Ling Chen#",
        "journal":  "The Journal of Cell Biology",
        "citation":  "214(7):789-91",
        "image":  "publication-media/2016_JCB.png",
        "sourceUrl":  "https://pubmed.ncbi.nlm.nih.gov/27646270/",
        "links":  [
                      {
                          "url":  "https://pubmed.ncbi.nlm.nih.gov/27646270/",
                          "label":  "PubMed"
                      },
                      {
                          "url":  "https://pmc.ncbi.nlm.nih.gov/articles/PMC5037413/",
                          "label":  "PMC"
                      },
                      {
                          "url":  "https://doi.org/10.1083/jcb.201609008",
                          "label":  "DOI"
                      }
                  ]
    },
    {
        "year":  2016,
        "title":  "Unusual Processing Generates SPA LncRNAs that Sequester Multiple RNA Binding Proteins.",
        "authors":  "Huang Wu*, Qing-Fei Yin*, Zheng Luo*, Run-Wen Yao, Chuan-Chuan Zheng, Jun Zhang, Jian-Feng Xiang, Li Yang, Ling-Ling Chen#",
        "journal":  "Molecular Cell",
        "citation":  "64(3):534-548",
        "image":  "publication-media/2016_MC.png",
        "sourceUrl":  "https://pubmed.ncbi.nlm.nih.gov/27871485/",
        "links":  [
                      {
                          "url":  "https://pubmed.ncbi.nlm.nih.gov/27871485/",
                          "label":  "PubMed"
                      },
                      {
                          "url":  "https://doi.org/10.1016/j.molcel.2016.10.007",
                          "label":  "DOI"
                      }
                  ]
    }
];
